awslabs/osml-cdk-constructs

.eslintrc.yaml
.gitignore
.pre-commit-config.yaml
lib/model_runner/mr_dataplane.ts

… publishing
Updating paths for model-runner build to reflect imagery-toolkit PyPi publishing

Updating paths for model-runner build 

---

.eslintrc.yaml
.gitignore
.pre-commit-config.yaml
lib/model_runner/mr_dataplane.ts

Updating core model runner dataplane construct to properly initialize.

Model runner update

---

lib/model_runner/mr_dataplane.ts
lib/osml/osml_account.ts

Updating CDK constructs to import the published docker container for model-runner.

Updating to leverage main published model-runner docker container

---

package-lock.json
package.json
tsconfig.json

*Issue #, if available:* N/A
*Description of changes:* Changing the types to point to dist instead of lib. Adding types to the exclude portion of tsconfig. 

Npm publish dist

---

package.json

*Description of changes:* Incrementing version for new release.

Incrementing npm package version number

---

README.md
package.json

*Description of changes:* Updating the README so it explains what constructs we're exporting and generally what they do. 

Update README to explain the constructs it exports

---

.github/workflows/publish.yml
package-lock.json

*Description of changes:* Doing an `npm i` results in updates to the package-lock.json. This PR will update it so the npm package has the most up to date package-lock.json. 

Update package lock

---

.github/workflows/publish.yml
README.md
lib/model_runner/mr_testing.ts
lib/osml/osml_bucket.ts
package-lock.json
package.json

Back merge to dev

---

lib/osml/osml_vpc.ts

Enabling VPC endpoints for OSML deployments to optimize/reduce network costs. 

Enabling VPC endpoints

---

lib/osml/osml_sm_endpoint.ts

Adding tags to, and increasing the default volume for, our sage maker endpoint constructs.
*Testing:*
Deployed and tested against latest baseline and w/ integration tests and workflows.

fix: fix model redeploys

---

package-lock.json
package.json

ci: version bump to v1.1.3

---

package-lock.json

Running ``npm upgrade --save`` to update back deps

fix: npm upgrade

---

lib/osml/model_runner/testing/mr_model_endpoints.ts

Updating to fix stack dependencies on generated ECR repositories when isDev flag is set to false.

release: update dependancy from endpoints on ECR repos

---

package-lock.json
package.json

fix: merge release into dev 

---

.github/workflows/notify-guidance-repo.yml
.github/workflows/npm-build.yml
.github/workflows/npm-publish.yml
.github/workflows/osml-cdk-constructs-build.yml
.github/workflows/osml-cdk-constructs-publish.yml

- Created npm run build workflow
- Created npm run publish workflow
- Created notify guidance repo workflow

Improve Github workflows

---

.github/workflows/npm-publish.yml

- The workflow was throwing an error that I have used the wrong `on` condition. It was looking for `workflow_call`. 

fix: Update 'on' condition

---

lib/osml/model_endpoints/osml_sm_endpoint.ts

Removing volumes from SM endpoints as they don't work with ml.gx instances.

fix: remove sm endpoint volume

---

lib/osml/tile_server/ts_dataplane.ts

Fixing load balancer bugs in tile server cdk

fix: updating tile server cdk

---

lib/osml/tile_server/ts_dataplane.ts

Updating port to run the container to fix broken deployment.

fix: fixing continer port bug

---

lib/osml/tile_server/roles/ts_lambda_role.ts
lib/osml/tile_server/roles/ts_task_role.ts
lib/osml/tile_server/ts_dataplane.ts

*Issue #, if available:* n/a
- Created a Lambda function which takes in the sweeper function from `osml-tile-server` package and attach it to the SQS DLQ so whenever there's a message in the DLQ, the lambda function will pick it up and process it.

feat: TS Lambda Sweeper

---

lib/osml/tile_server/ts_dataplane.ts

- In `Dockerfile`, we created a new user (`tileserver`) but that said user wasn't able to create sub directories in EFS due to the permission issues. To work around that, we have to setup the Access Point for the `tileserver` user which can create files/subdirectories inside the efs mount. 

fix: Efs permissions for Fargate Cluster

---

lib/osml/tile_server/roles/ts_task_role.ts
lib/osml/tile_server/ts_dataplane.ts

- Restrict all services permissions to least permissions needed

fix: Restrict TaskRole permissions

---

lib/osml/tile_server/ts_dataplane.ts
package-lock.json

Fixing public load balancer configuration for tile server such that we keep the load balancer and IPs private.

fix: fixing public load balancer configuration for tile server

---

lib/osml/tile_server/roles/ts_lambda_role.ts
lib/osml/tile_server/ts_dataplane.ts

- Add Lambda function to execute TS integ test

feat: TS Lambda Integ Test

---

lib/osml/model_runner/autoscaling/mr_autoscaling.ts
lib/osml/model_runner/mr_dataplane.ts

fix: minor dataplane updates

---

lib/osml/model_runner/monitoring/mr_monitoring.ts

These changes replace the OSML dashboard with an OSML-ModelRunner dashboard that uses the new standardized metrics produced by model runner [PR: #59](https://github.com/aws-solutions-library-samples/osml-model-runner/pull/59).

feat: new metrics dashboard example

---

lib/osml/model_endpoint/me_container.ts
lib/osml/model_runner/monitoring/mr_monitoring.ts
lib/osml/model_runner/mr_container.ts
lib/osml/osml_account.ts
lib/osml/tile_server/ts_container.ts

Release dev to main 

---

.github/copyright.yaml
.pre-commit-config.yaml
lib/index.ts
lib/osml/model_endpoint/me_container.ts
lib/osml/model_endpoint/me_http_endpoint.ts
lib/osml/model_endpoint/me_sm_endpoint.ts
lib/osml/model_endpoint/roles/me_http_role.ts
lib/osml/model_endpoint/roles/me_sm_role.ts
lib/osml/model_runner/autoscaling/mr_autoscaling.ts
lib/osml/model_runner/monitoring/mr_monitoring.ts
lib/osml/model_runner/mr_container.ts
lib/osml/model_runner/mr_dataplane.ts
lib/osml/model_runner/roles/mr_task_role.ts
lib/osml/model_runner/testing/mr_endpoints.ts
lib/osml/model_runner/testing/mr_imagery.ts
lib/osml/model_runner/testing/mr_sync.ts
lib/osml/osml_account.ts
lib/osml/osml_bucket.ts
lib/osml/osml_ecr_deployment.ts
lib/osml/osml_queue.ts
lib/osml/osml_repository.ts
lib/osml/osml_table.ts
lib/osml/osml_topic.ts
lib/osml/osml_vpc.ts
lib/osml/tile_server/roles/ts_lambda_role.ts
lib/osml/tile_server/roles/ts_task_role.ts
lib/osml/tile_server/testing/ts_imagery.ts
lib/osml/tile_server/ts_container.ts
lib/osml/tile_server/ts_dataplane.ts
test/osml-cdk-constructs.test.ts

Updating copyright and adding pre-commit hooks to manage it going forward.

chore: update copyright

---

package-lock.json
package.json

chore: rebase dev branch

---

.github/workflows/documentation-publish.yml
.github/workflows/osml-cdk-constructs-build.yml
.github/workflows/osml-cdk-constructs-publish.yml
.gitignore
README.md
package-lock.json
package.json
tsconfig.json

- Update the README to reflect on the current changes
- Add new documentation workflow to generate the doc page

feat: Generate documentation and Update README

---

lib/osml/model_endpoint/roles/me_http_role.ts
lib/osml/model_endpoint/roles/me_sm_role.ts
lib/osml/model_runner/autoscaling/mr_autoscaling.ts
lib/osml/model_runner/mr_dataplane.ts
lib/osml/model_runner/roles/mr_execution_role.ts
lib/osml/model_runner/roles/mr_task_role.ts
lib/osml/tile_server/roles/ts_execution_role.ts
lib/osml/tile_server/roles/ts_lambda_role.ts
lib/osml/tile_server/roles/ts_task_role.ts
lib/osml/tile_server/ts_dataplane.ts

- Eliminate all unnecessary permissions. Grant only the permissions required to perform the task.
- Differentiating between ECS Task Role vs ECS Execution Role
**Test:**
- Ran TileServer Integration Test and MR Integration Test. All succeeded. 

fix: Restrict to least IAM permissions

---

lib/osml/model_endpoint/me_container.ts
lib/osml/model_runner/mr_container.ts
lib/osml/tile_server/ts_container.ts

- Update container's tags to use the `latest` tag 

fix: update containers tag to use latest tag

---

package.json

* version bump to v1.9.0 to include the following changes:
* build: updating to support trunk based developmen
* feat: implementing data intake component

ci: version bump to v1.9.0

---

.github/workflows/build.yml

- When creating a release, it failed due to the `build.yml` not condition the `workflow_call` condition
- https://github.com/aws-solutions-library-samples/osml-cdk-constructs/actions/runs/9274849713

ci: update build.yml on condition

---

lib/osml/osml_account.ts
lib/osml/osml_authenticate.ts
lib/osml/tile_server/ts_dataplane.ts
test/osml/tile_server/ts_dataplane.test.ts
test/test_account.ts

- Implement ALB auth using your OIDC configuration

feat: implement ALB auth feature

---

lib/index.ts
lib/osml/model_runner/testing/mr_sync.ts
package-lock.json
package.json

- Add `osml_authenticate` to index file
- Bump up the version to `v1.10.0`
- Update the `package-lock.json` file
- Update `MRSync` config for kinesis stream and s3  

fix: update index.ts, package-lock.json, and bump up the version

---

lib/osml/model_runner/testing/mr_sync.ts

This will make the stream for Model Runner clean up correctly.

chore: setting removal policy on Kinesis stream

---

package-lock.json
package.json

ci: version bump to v1.10.3

---

lib/osml/osml_vpc.ts

Adding more verbose and explanatory comments in the OSML VPC class to clarify the functionality it's provides the user. 

chore: cleaning up OSMLVPC construct

---

.github/workflows/build.yml

- Based on previous PRs, there were ton of annotations for the uncovered tests or branches which makes it unreadable when reviewing the codes. Therefore, I have updated the `annotations` within the jest to report only failed test cases.

ci: update jest annotations to failed only

---

README.md

- Update README.md to include data catalog 

chore: update README.md to include data catalog

---

package-lock.json
package.json

- Update `osml-cdk-constructs` to `v1.11.0`

ci: version bump to v1.11.0

---

lib/osml/data_catalog/dc_dataplane.ts
lib/osml/osml_vpc.ts
package-lock.json
package.json
test/osml/data_catalog/Dockerfile
test/osml/data_catalog/dc_dataplane.test.ts
test/osml/data_intake/di_dataplane.test.ts
test/osml/tile_server/ts_dataplane.test.ts

- Some AWS accounts may have OpenSearch service role but some do not. Therefore, add additional checking to see if the OpenSearch service exist, if not, it will create one. 
```
Invalid request provided: Before you can proceed, you must enable a service-linked role to give Amazon OpenSearch Service permissions to access your VPC.
```

hotfix: check if service role exists for OpenSearch

---

package-lock.json
package.json

- Update `osml-cdk-constructs` to `v1.12.0`
* hotfix: check if service role exists for OpenSearch
* feat: add authorizer lambda and restapi construct
* fix: removed unused model property and allow configuration of TS lambda asset
* fix: migrate ALB OIDC to API auth lambda
* fix: adding parameter for lambda runtime

ci: version bump to v1.12.0

---

package-lock.json
package.json

- Update `osml-cdk-constructs` to `v1.12.1`
* fix: update maxAzs vpc prop by @natekruse-aws in https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/126
* fix: add maxAzs config by @natekruse-aws in https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/127
* fix: implement regional config by @natekruse-aws in https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/129

ci: version bump to v1.12.1

---

lib/osml/model_runner/mr_dataplane.ts
lib/osml/tile_server/ts_dataplane.ts
lib/osml/utils/regional_config.ts
lib/osml/utils/regional_configs.ts

Our containers were using the IAD S3 endpoint in GovCloud, breaking GDAL's ability to connect to S3. Updated the containers to use the endpoint specified in the regional configuration.

fix: update s3 endpoint

---

package-lock.json
package.json

Bumping the version in the package.json

ci: version bump to v1.13.1

---

package-lock.json
package.json

Version bump to v1.13.2 in package.json.

build: version bump to v1.13.2

---

package-lock.json
package.json

Bumping version to v2.0.0 in ``package.json`` file and updating ``package-lock.json``.

ci: version bump to v2.0.0

---

package-lock.json
package.json

* Removing ECR deployment dependency that is no longer used.
* Updating version for follow up release to v2.0.1

chore: removing dep dependancy and updating to v2.0.1

---

package-lock.json
package.json

Updating version in package.json to v2.0.2

build: updating version to v2.0.2

---

lib/osml/data_catalog/dc_dataplane.ts
lib/osml/data_intake/di_dataplane.ts
lib/osml/model_endpoint/me_test_endpoints.ts
lib/osml/model_runner/mr_dataplane.ts
lib/osml/osml_vpc.ts
lib/osml/tile_server/ts_dataplane.ts

- Removed some dead codes
- Set `mutable` to false when using the imported roles

fix: set 'mutable' to false when using imported roles

---

lib/osml/model_runner/mr_dataplane.ts

- An ability to pass their own existing topic arn rather than generate a new topic

fix: pass imported topic arn

---

package-lock.json
package.json

build: version bump to v2.0.3

---

package-lock.json
package.json

Bumping version to 2.0.4 in `package.json` for release.

build: version bump to v2.0.4

---

lib/osml/data_intake/di_dataplane.ts
lib/osml/osml_container.ts
package-lock.json
package.json

- Renamed `CONTAINER_SOURCE_URI` to `CONTAINER_URI`
- Updated on parsing the CONTAINER_URI if we pass the full arn along with the tag. 
- Removed `CONTAINER_TAG` since it was never used in other components 
- Update `osml-cdk-constructs` version to `2.0.5` and update dependencies which will resolve this [PR](https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/154)
Tested using this `cdk.context.json`
```
{
"projectName": "OSML",
"account": {
"id": "<account id>",
"region": "us-west-2",
"prodLike": false
},
"modelRunner": {
"deploy": true,
"config": {
"CONTAINER_URI": "arn:aws:ecr:us-west-2:<account id>:repository/osml-nightly-dev:osml-model-runner"
}
},
"tileServer": {
"deploy": false,
"config": {
"DEPLOY_TEST_COMPONENTS": false, …
```

fix: add partition in osml_container

---

lib/osml/osml_container.ts
package-lock.json
package.json

- add extractedTag for dockerImageCode
- Update version to 2.0.6

fix: add extractedTag for dockerImageCode

---

package-lock.json
package.json

release: v2.0.7

---

package-lock.json
package.json

Updating package to release version v2.0.8.

release: v2.0.8

---

.eslintrc.yaml
lib/index.ts
test/osml/utils/base_config.test.ts
test/osml/utils/regional_config.test.ts

1. **Unit Tests:**
- This PR adds comprehensive unit tests for the following configuration modules:
- **BaseConfig**: Ensures proper initialization, default values, and dynamic property assignments.
- **RegionalConfig**: Tests region-specific configurations and default fallback behavior.
2.**Fixing Linting:**
- Removed broken line ``- allowShortCircuit: true`` in ``.eslintrc.yaml``
3.**Updating ``index.ts:``**
- Adding export for ``regional_config``

chore: add missing unit tests

---

lib/osml/tile_server/ts_dataplane.ts

This adds an additional optional environment variable FASTAPI_ROOT_PATH to set the api root path in the application.  It also updates the names of other tile server environment variables to avoid ambiguity.

feat: add environment variables for api root paths

---

lib/osml/model_endpoint/me_http_endpoint.ts
lib/osml/model_endpoint/me_sm_endpoint.ts
lib/osml/model_endpoint/me_test_endpoints.ts
lib/osml/model_runner/mr_dataplane.ts
lib/osml/osml_table.ts
test/osml/model_runner/mr_dataplane.test.ts

This PR updates the METestEndpoints to create two variants of the sample flood model.  Each variant has a different flood volume to enable testing of the model variant selection feature of Model Runner.

feat: create multiple flood model variants

---

lib/osml/model_endpoint/me_sm_endpoint.ts
lib/osml/model_endpoint/me_test_endpoints.ts

This adds an additional SageMaker endpoint used to support integration tests.  The endpoint has both the centerpoint model and the aircraft model deployed to the same endpoint but running in different containers.  This will allow tests to verify that Model Runner can support the `TargetContainerHostname` property in the image request.

feat: add a test multi-container endpoint
