awslabs/osml-cdk-constructs

- .github/workflows/publish.yml
*Description of changes:* Instead of publishing to npm on release, publish to npm on pushes to main.
> Publish to npm on every push to main

- .github/workflows/publish.yml
*Description of changes:* Automatically increment the version number of the package.json so we publish a new version to NPM. 
`phips28/gh-action-bump-version` is a tool which will increment the version based on the commit message. By default it will increment patch, but if a commit contains a message like "Feature" it will increment the minor version, and for commits like "major" or "refactor" it increments the major version. 
> Add auto-increment steps to publish workflow

- lib/model_runner/mr_testing.ts
- lib/osml/osml_bucket.ts
- When destroying the test, it failed to delete the stack because the `access-logs` still have logs in it. Therefore, disabling the `versioned` property fixes the issue. The stack now be able to delete the `access-log` bucket. 
> Fixed bucket failed to delete

- lib/model_runner/mr_dataplane.ts
- lib/model_runner/mr_testing.ts
- lib/osml/osml_http_endpoint.ts
Fix the passing in of the correct security groups to sub components of the testing resources deployment. Adding private subnets to addition testing resources where they should be specified. Moving to using ephemeral storage for bucket deployment lambda since efs isn't enabled for all customers.   
> hotfix: fix sg/modelUri passthrough

- lib/osml/model_runner/testing/mr_model_endpoints.ts
Updating such that the ECR repositories that are created when isDev is false are properly depended on by the Endpoints.
> fix: endpoint ecr dependancy

- lib/osml/model_endpoints/osml_endpoint_container.ts
Updating osml_endpoint_container.ts to fix typo in Construct name
> fix: updating osml_endpoint_container.ts

- .github/workflows/osml-cdk-constructs-publish.yml
- This workflow only works if merged in main branch. I need to update this workflow such that it should notify the guidance repo if merged into dev branch as well.
> fix: Update `needs` condition for Notify workflow

- lib/osml/tile_server/ts_dataplane.ts
*Issue #, if available:* n/a
- Update the partition key for tile server table since Tile Server repo relies on `viewpoint_id` as a partition name 
> fix: Update partition key for tileserver table

- lib/osml/tile_server/ts_dataplane.ts
Adding the ephemeralStorage parameter to the Tile Server task definition.
> adding ephemeral storage parameter to tile server task definition

- lib/osml/tile_server/ts_dataplane.ts
Implementing tile server health check for ECS tasks. Deployed and tested in dev account to verify healthy status checks out on the ECS tasks.
> feat: implementing tile server health check for ECS tasks

- lib/osml/model_runner/mr_dataplane.ts
Fixing a bug where the custom configuration was not being set for the dataplane construct when it was passed in.
*Testing:*
Passed in a custom config and validated it deployed correctly.
> fix: dataplane config bug

- lib/osml/model_endpoint/me_container.ts
- lib/osml/model_runner/mr_container.ts
- lib/osml/osml_account.ts
- lib/osml/tile_server/ts_container.ts
* Removing model runner specific configurations from the accounts.ts file in favor of simplifying to approach new module, i.e. tile sever deployments. Module specific configurations should be done at a stack level.
> feat: updating account configurations

- lib/index.ts
- lib/osml/tile_server/testing/ts_test_runner.ts
- lib/osml/tile_server/testing/ts_test_runner_container.ts
- test/osml/tile_server/testing/ts_test_runner_container.test.ts
Adding dependency between tile server test lambda and ECR repo containing the pre-built image.  Previously lambda would fail because it was checking for the image before it had finished copying from dockerhub.
> fix: adding dependency between tile server test lambda and ecr repo

- lib/osml/osml_bucket.ts
- package.json
- `autoDeleteObjects` for S3 Bucket and `emptyOnDelete` for ECR Repo
- emptyOnDelete does not exist for S3 Bucket according to the [aws-cdk package](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.Bucket.html#autodeleteobjects)
> hotfix: update Bucket property to use autoDeleteObjects

- lib/osml/osml_vpc.ts
Seeing this - migrating
```
/** @deprecated - Use InterfaceVpcEndpointAwsService.CLOUDWATCH_MONITORING instead. */
static readonly CLOUDWATCH: InterfaceVpcEndpointAwsService;
```
> chore: fixing depreciated CLOUDWATCH VPC endpoint setting

- lib/osml/data_intake/roles/di_lambda_role.ts
- package-lock.json
- package.json
- Add missing VPC permission for lambda role due to the following error caught during the deployment
```
"The provided execution role does not have permissions to call CreateNetworkInterface on EC2"
```
- Bump up the version to `v1.10.2`
> hotfix: add missing VPC permission for lambda and version bump

- lib/index.ts
- lib/osml/data_catalog/Dockerfile
- lib/osml/data_catalog/dc_dataplane.ts
- lib/osml/osml_authorizer/lambda/lambda_function.py
- lib/osml/osml_authorizer/osml_authorizer.ts
- lib/osml/osml_restapi.ts
- package.json
- test/osml/data_catalog/dc_dataplane.test.ts
- Add Authorizer Lambda construct
- Integrate the Authorizer Lambda with APIGW in Data Catalog service
- In order to use Data Catalog service, you must enable `Auth` in your `target_account.json`. We do not want to expose the APIGW publicly and freely accessible. 
> feat: add authorizer lambda and restapi construct

- lib/osml/model_runner/monitoring/mr_monitoring.ts
- lib/osml/tile_server/ts_dataplane.ts
- test/osml/model_runner/monitoring/mr_monitoring.test.ts
These changes are minor updates to support expanded examples in the guidance repository. Updates include:
- The unused "model" configuration option has been removed from from the ModelRunner monitoring stack.
- The dashboard has been updated to align with the documented examples in the ModelRunner repository.
- The TileServer construct has been updated to allow configuration of the source path for the DLQ lambda. 
> fix: removed unused model property and allow configuration of TS lambda asset

- lib/osml/data_catalog/dc_dataplane.ts
- lib/osml/osml_vpc.ts
- test/osml/data_catalog/dc_dataplane.test.ts
**Issue #, if available:** 
This PR resolves the issue of deploying the VPC stack into a non-ISO AWS region with less than 3 AZs. 
```
Template error: Fn::Select cannot select nonexistent value at index 2
```
The `Fn::GetAzs` CFN function was returning more AZs than the VPC could create subnets in. Specifically, in us-west-1.
Providing the customer with the option to specify the number of AZs they want to use, otherwise default to 2.
I also updated the DCDataplane Domain to use the same number of AZs as the VPC rather than an arbitrary config value.
> fix: update maxAzs vpc prop

- lib/osml/osml_vpc.ts
- lib/osml/utils/region_az_config.ts
Maintaining a static config of the default VPC AZs deployed in each region. This prevents us from breaking existing customers if they already have a VPC deployed with more than 2 AZs. Customers have the option to change this property by setting `maxAzs` if they want.
> fix: add maxAzs config

- lib/osml/data_intake/di_dataplane.ts
Increasing data intake lambda timeouts to 15 minutes to handle the largest / longest running images possible.
> fix: increasing lambda timeouts for data intake

- lib/osml/data_intake/di_container.ts
Fixing container repo link to data intake container to correctly point at the published [repository](https://hub.docker.com/repository/docker/awsosml/osml-data-intake-intake/general)
> chore: fixing container repo link to data intake container

- lib/osml/data_catalog/dc_dataplane.ts
Restoring the leading `/` to the data catalog's `STAC_FASTAPI_ROOT_PATH`.
> fix: adding leading / to fastapi path to delimit domain

- lib/osml/model_runner/mr_dataplane.ts
In this context, a sink is the destination of a data flow (S3, Kinesis, etc.) so sync is incorrect and may cause confusion.
> fix: rename sync to sink

- lib/osml/model_runner/roles/mr_execution_role.ts
- lib/osml/model_runner/roles/mr_task_role.ts
Removing dead references to firelens.
> chore: remove firelens references

- lib/osml/model_endpoint/me_test_endpoints.ts
- lib/osml/model_endpoint/roles/me_sm_role.ts
- lib/osml/model_runner/mr_dataplane.ts
- lib/osml/model_runner/roles/mr_execution_role.ts
- lib/osml/model_runner/roles/mr_task_role.ts
- lib/osml/tile_server/roles/ts_execution_role.ts
- lib/osml/tile_server/roles/ts_lambda_role.ts
- lib/osml/tile_server/roles/ts_task_role.ts
Updating roles to longer use default configurations when setting permissions, this avoids deployments breaking when users have provided custom configurations that don't match the defaults. Additionally updating the dockerfile path to match upstream changes to the ``osml-models`` package.
> fix: update roles

- lib/osml/tile_server/roles/ts_task_role.ts
This PR adds the DeleteItem permission to the Tile Server Task Policy to allow the TS router to delete viewpoints.
> fix: add DeleteItem permission to TSTaskPolicy

- .github/workflows/build.yml
- .pre-commit-config.yaml
- lib/osml/data_catalog/dc_dataplane.ts
- lib/osml/data_intake/di_dataplane.ts
* Modifies the ingest topic names in the DI and DC constructs to ensure they are unique. The change prevents resource collisions when both constructs are integrated directly within the same CDK project. Unique topic names eliminate naming conflicts, ensuring reliable deployment of both DI and DC constructs and supports scenarios where DI and DC are deployed independently into the same account.
* Updates the Github actions to use latest versions to resolve warnings showed as part of this build.
* Pre-commit logic has been updated to avoid breaks at the turn of the new year to explicit run pre-commit against files that changed as part of each commit.
By submitting this pull request, I …
> fix: updating DI and DC ingest topic names to be unique

- lib/osml/model_runner/mr_dataplane.ts
- test/osml/model_runner/mr_dataplane.test.ts
This change adds a new DynamoDB table to the ModelRunner dataplane construct. This new table is for use by future job scheduler implementations that need to keep a record of requests pulled from the SQS queue that have not yet been started. Changes include creation of the table and passing of the table's name into the ModelRunner application via a environment variable in the ECS task configuration.
Unit tests were updated and changes were manually verified by deploying a new stack and confirming that the table and environment were updated as expected.
> feat: add MROutstandingImageJobsTable to MRDataplane

- lib/osml/model_runner/mr_dataplane.ts
This change adds the URL of the image DLQ to the MR task environment. The new load based scheduler needs this information so it can move tasks that have been retried too many times to the DLQ. This information wasn't needed in the past because we were getting that behavior for free from SQS. Submitted as a fix because this change was mistakenly omitted from the previous feature which added the region request table and other infrastructure needed by the scheduler.
Updates were tested in a development environment by deploying the new stacks.
> fix: add IMAGE_DLQ parameter to MR task environment

- lib/osml/model_endpoint/me_http_endpoint.ts
- lib/osml/model_runner/mr_dataplane.ts
- lib/osml/osml_container.ts
- lib/osml/tile_server/ts_dataplane.ts
- test/osml/osml_container.test.ts
This PR enhances the `buildFromRepository()` method by **adding support for importing ECR repositories via ARN (`REPOSITORY_ARN`)** and **improving the extraction and handling of container image URIs**. Previously, the code:
- **Did not support repository ARNs**, requiring only `CONTAINER_URI`.
- **Incorrectly checked for an ECR ARN instead of an ECR URI**.
- **Defaulted to `"latest"` even when a tag was present** in the `CONTAINER_URI`.
- **Adds support for `REPOSITORY_ARN`**, allowing users to provide an **ECR repository ARN** instead of a full image URI.
- **Ensures only one of `CONTAINER_URI` or `REPOSITORY_ARN` is provided**, preventing misconfigurations.
- **Extracts and respects image tags** from `CONTAINER_URI` (e.g., `repo-name:tag`).
- **Fixes ECR …
> fix: correctly parse ECR URIs and tags to OSMLContainer
